name = "bookkeeping-bot"
main = "worker.js"
compatibility_date = "2025-06-09"

[vars]
BOT_TOKEN = "8638712861:AAFaWkeCAfQp07cCrUi3YX8QFWMGf-7_gGM"
ADMIN_IDS = ""

[[kv_namespaces]]
binding = "KV"
id = ""